update scripts

diff --git a/scripts/standalone b/scripts/standalone
--- a/scripts/standalone
+++ b/scripts/standalone
@@ -1,16 +1,26 @@
 #!/bin/bash
 cd /Users/bhauman/workspace/specly
 
+if [ -d "src/strictly_specking_standalone" ]; then
+    echo 'Error:: already a standalone!!!'
+    exit 1 
+fi
+
 sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e 's/clojure.spec/strictly-specking-standalone.spec/g' test/strictly_specking/*.clj src/strictly_specking/*.clj dev-resources/test_specs/*.clj
 rm test/strictly_specking/*.bak src/strictly_specking/*.bak dev-resources/test_specs/*.bak
 
 mv test/strictly_specking test/strictly_specking_standalone
-mv src/strictly_specking src/strictly_specking_standalone
+mv src/strictly_specking src/strictly_specking_standalone 
+
+mkdir -p src/strictly_specking_standalone/spec
+cp dev-resources/1.6_compat_spec/spec.clj src/strictly_specking_standalone/spec.clj
+cp dev-resources/1.6_compat_spec/spec/gen.clj src/strictly_specking_standalone/spec/gen.clj
+
 
 #sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e 's/clojure.spec/strictly-specking-standalone.spec/g' src/strictly_specking/*.clj
 # rm src/strictly_specking/*.bak
 #mv src/strictly_specking src/strictly_specking_standalone
 
-#sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e  src/1.6_compat_spec/spec.clj src/1.6_compat_spec/spec/gen.clj
+#sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e  dev-resources/1.6_compat_spec/spec.clj dev-resources/1.6_compat_spec/spec/gen.clj
 
 
diff --git a/scripts/undo-standalone b/scripts/undo-standalone
--- a/scripts/undo-standalone
+++ b/scripts/undo-standalone
@@ -1,8 +1,22 @@
 #!/bin/bash
 cd /Users/bhauman/workspace/specly
 
+if [ -d "src/strictly_specking" ]; then
+    echo "Error:: already a not a standalone!!!!"
+    exit 1 
+fi
+
+rm src/strictly_specking_standalone/spec/gen.clj
+rmdir src/strictly_specking_standalone/spec
+rm src/strictly_specking_standalone/spec.clj
+
 mv test/strictly_specking_standalone test/strictly_specking
+
 mv src/strictly_specking_standalone src/strictly_specking
+
+if [ -d "src/strictly_specking_standalone" ]; then
+    rmdir src/strictly_specking_standalone 
+fi
 
 sed -i.bak -e 's/strictly-specking-standalone.spec/clojure.spec/g' -e 's/strictly-specking-standalone/strictly-specking/g' test/strictly_specking/*.clj src/strictly_specking/*.clj dev-resources/test_specs/*.clj
 
